# tasks to complete before running roles

- hosts: all
  tags: always
  connection: local
  become: true

  pre_tasks:

    - name: pre-run | install packages
      apt:
        name: "{{ item }}"
        state: latest
      loop: [ 'htop', 'wget', 'curl', 'vim', 'sudo', 'nano']  

- hosts: all
  tags: base
  become: true
  roles:
    - base

- hosts: server
  tags: server
  become: true
  roles:
    - server

- hosts: postgres
  tags: postgres
  become: true
  roles:
    - server
    - docker
    - rolesfromtags
    
- hosts: all
  tags: finalize
  become: true
  roles:
    - finalize
