# tasks to complete before running roles

- hosts: all
  tags: always
  connection: local
  become: true

  pre_tasks:

    - name: pre-run | install packages
      apt:
        name: "{{ item }}"
        state: latest
      loop: [ 'htop', 'wget', 'curl', 'vim', 'sudo', 'nano']  

    - name: pre-run | add ansible user
      user:
        name: ansible.cron
        system: yes

    - name: pre-run | set up sudo for ansible user
      copy:
        src: files/sudoer_ansible.cron
        dest: /etc/sudoers.d/ansible.cron
        owner: root
        group: root
        mode: 0440


- hosts: all
  tags: base
  become: true
  roles:
    - base

- hosts: server
  tags: server
  become: true
  roles:
    - server

- hosts: postgres
  tags: postgres
  become: true
  roles:
    - server
    - docker
    - postgress
    
- hosts: all
  tags: finalize
  become: true
  roles:
    - finalize
