version: '2'

services:
  postgresql:
    image: postgres:14
    container_name: postgres
    ports:
      - 9001:9001
    volumes:
      - /docker_data/postgres/data:/var/lib/postgresql/data
    restart: always