  vars_prompt:

    - name: username
      prompt: What is your username?
      private: no

    - name: password
      prompt: What is your password?

- name: duosecurity | install required system packages
  dnf:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop: [ 'duo-unix']

- name: duosecurity | change file permissions
  ansible.builtin.file:
    path: /usr/sbin/login_duo
    owner: scraane
    group: scraane
    mode: '0400'