- name: docker | install dependencies
  apt:
    name: 
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg2
        - software-properties-common
    state: present
    update_cache: no


- name: Install bottle python package
  pip:
    name:
        - docker-compose
        - docker
    
- name: docker | Add Docker GPG apt Key
  apt_key:
    url: "{{ docker_apt_gpg_key }}"
    state: present

- name: docker | Add Docker Repository
  apt_repository:
    repo: "{{ docker_apt_repository }}"
    state: present
    update_cache: true
    
- name: docker | Update apt and install docker-ce
  apt:
    name: docker-ce
    state: present
    update_cache: false

- name: docker | Run and enable docker
  service:
    name: docker
    state: started
    enabled: true

- name: docker | add remote "scraane" user to "docker" group
  remote_user: scraane
  user:
    name: "scraane"
    group: "docker"

- name: docker | create docker-data directory if it does not exist
  file:
    path: /docker_data
    state: directory
    mode: '0755'
    owner: root
    group: docker

  
- name: docker | docker-compose | Install or upgrade docker-compose
  get_url: 
    url : "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: 'a+x'
    force: yes
    
- name: docker | copy update.sh script
  copy:
    src: files/update.sh
    dest: /docker_data/update.sh
    owner: root
    group: docker
    mode: 0755

- name: docker | create portainer-agent directory if it does not exist
  file:
    path: /docker_data/portainer-agent
    state: directory
    mode: '0755'
    owner: root
    group: docker

- name: docker | copy portainer-agent compose script
  copy:
    src: files/portaineragent.yml
    dest: /docker_data/portainer-agent/docker-compose.yml
    owner: root
    group: docker
    mode: 0755
    
- name: docker | deploy portainer-agent
  docker_compose:
    project_src: /docker_data/portainer-agent/
    files: /docker_data/portainer-agent/docker-compose.yml
