- name: base | locale | set timezone to Europe/Amsterdam
  copy: content="Europe/Amsterdam\n" dest=/etc/timezone owner=root group=root mode=0644
  register: timezone
  
- name: base | locale | set timezone to Europe/Amsterdam if changed
  command: dpkg-reconfigure -f noninteractive tzdata
  when: timezone.changed
