- name: base | neofetch
  block:
    - name: base | neofetch | install
      apt:
        name: neofetch
        state: latest

    - name: base | neofetch | add to motd
      shell: echo "echo" > /etc/profile.d/mymotd.sh && echo "neofetch" >> /etc/profile.d/mymotd.sh && chmod +x /etc/profile.d/mymotd.sh
